Register
arkavidia-hmif/arkavidia-frontend pull request #4
Opened 2020-10-26 13:50 UTC by akromiafif

2020-10-28 02:23 UTC, jrandiny commented
Untuk desktop terlalu lebar, diwrap "container" saja
Untuk mobile juga alignmentnya masih ada yang salah
Tombol hovernya belum ada, pakai component yang sudah ada saja

Untuk commit jg kenapa ada yang duplikat ya dengan master

2020-10-28 02:48 UTC, jrandiny requested changes

2020-10-28 02:48 UTC, jrandiny commented on components/Layout.tsx
> -export default Layout
em why?

2020-10-28 02:48 UTC, jrandiny commented on components/Register.tsx
> +function Register() {
Typing typescript jangan lupa

2020-10-28 02:48 UTC, jrandiny commented on components/Register.tsx
> +          <button type="submit">Daftar</button>
Pakai component yang sudah ada untuk tombol

2020-10-28 02:48 UTC, jrandiny commented on components/Register.tsx
> +            background: linear-gradient(180deg, rgba(255, 255, 255, 0.26) 20.31%, rgba(255, 163, 186, 0.38) 53.65%, rgba(168, 142, 215, 0.56) 100%);
Pakai background di component `Layout`

2020-10-28 02:48 UTC, jrandiny commented on components/Register.tsx
> +        <h1>Registrasi Akun</h1>
Pakai component `ColorfulHeader` saja

2020-10-28 02:48 UTC, jrandiny commented on components/Register.tsx
> +            font-size: 20px;
Kurang-kurangin pakai pixel

2020-10-28 02:48 UTC, jrandiny commented on package.json
> -}
why?

2020-10-28 02:48 UTC, jrandiny commented on components/Register.tsx
> +          form {
btw udah ada bootstrap ya kalau mau pake

2020-10-28 02:48 UTC, jrandiny commented on components/Register.tsx
> +    <div className="flex-container">
Bisa pakai bootstrap

2020-10-28 07:59 UTC, akromiafif commented on components/Register.tsx
> +          form {
belum belajar bootstrap sih kak jadi lebih nyaman pake css sendiri.

2020-10-28 07:59 UTC, akromiafif commented on package.json
> -}
nah ini ga ngerti kak tiba2 gitu wkwkwk

2020-10-29 14:14 UTC, jrandiny requested changes
Tolong resolve conflict

2020-10-30 11:40 UTC, jrandiny approved these changes

2020-10-30 11:40 UTC, merged