Event page
arkavidia-hmif/arkavidia-frontend pull request #7
Opened 2020-10-30 15:03 UTC by fabiansdp

2020-10-30 15:47 UTC, jrandiny requested changes
Tolong diperbaiki yang dicomment dan juga untuk url nanti pakai format seperti ini
```
/preevent/technocamp
/preevent/arkavidia-goes-to-school
/preevent/arkavidia-academy
/preevent/arkavidia-on-air
/event/it-festival
/event/arkavidia-talks
```
Untuk warna header juga ada yang salah seperti di halaman ITFest dan Arkavidia talks

Untuk yang timeline, lebarnya dikasih maks lebar sebesar sisanya yang di atasnya

2020-10-30 15:47 UTC, jrandiny commented on components/DateContainer.tsx
> +        <h3 key={index}>{date}</h3>
Jangan h3 untuk date

2020-10-30 15:47 UTC, jrandiny commented on components/pre-event/technocamp/BenefitBox.tsx
> +                font-size: 1.5em;
ada alasan kenapa bukan rem?

2020-10-30 15:47 UTC, jrandiny commented on components/pre-event/technocamp/Ribbon.tsx
> +                    font-size: 0.8rem;
Terlalu kecil, jangan < 1rem

2020-10-30 15:47 UTC, jrandiny commented on components/DateContainer.tsx
> +const DateContainer : React.FC<Props> = ({dates}) => (
Somehow kalau dilihat dia secara vertikal tidak ditengah tanggalnya

2020-10-31 00:50 UTC, fabiansdp commented on components/DateContainer.tsx
> +        <h3 key={index}>{date}</h3>
harusnya pakai apa ya kak?

2020-10-31 02:46 UTC, jrandiny approved these changes

2020-10-31 02:46 UTC, merged